Update planka-test.yml

diff --git a/.github/workflows/planka-test.yml b/.github/workflows/planka-test.yml
--- a/.github/workflows/planka-test.yml
+++ b/.github/workflows/planka-test.yml
@@ -46,7 +46,8 @@ jobs:
           echo "USER_EMAIL: $USER_EMAIL"
           echo "USER_PASSWORD: $USER_PASSWORD"
           echo "BASE_URI: $BASE_URI"
-    
+
+
       - name: Levantar Planka con Docker y esperar
         env:
           USER_EMAIL: ${{ secrets.USER_EMAIL }}
@@ -63,6 +64,29 @@ jobs:
             sleep 25
          done
          echo "Planka está en línea"
+
+
+      - name: Obtener token de Planka
+        run: |
+          echo "Haciendo login en Planka..."
+
+          RESPONSE=$(curl -s -X POST http://localhost:3000/api/users/token \
+            -H "Content-Type: application/json" \
+            -d "{\"email\": \"$USER_EMAIL\", \"password\": \"$USER_PASSWORD\"}" )
+
+          echo "Respuesta:"
+          echo "$RESPONSE"
+
+          TOKEN=$(echo $RESPONSE | jq -r '.token')
+
+          if [ "$TOKEN" = "null" ] || [ -z "$TOKEN" ]; then
+            echo "❌ ERROR: No se pudo obtener token de Planka."
+            exit 1
+          fi
+
+          echo "✔ Token obtenido correctamente"
+          echo "PLANKA_TOKEN=$TOKEN" >> $GITHUB_ENV
+
 
       - name: Inspect user_account table
         run: |
